#!/usr/bin/env bash
# Bash script that creates the file /var/run/myscript.pid containing its PID
trap "echo \"Y U no love?!\"; exit" SIGINT
trap "sudo rm /var/run/myscript.pid; exit" SIGQUIT
trap "echo \"I hate the kill command\"; sudo rm /var/run/myscript.pid; exit" SIGTERM

echo "$$" > /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	sleep 2
done
